### PR TITLE
Create save-on-startup-costs.md

### PR DESCRIPTION
**Pull request by jewelljones**
@ck7286 @seankeresey @ck7286 @jsha2007  - Should I change or add anything else?

### CODE REVIEW

**Comment by jsha2007** [comment]
@jewelljones
in the development paragraph: i'm not sure you actually save costs by tackling the risky features first, only reduce the risk of failing. Might be better to talk about prioritizing features instead?

**Comment by rmotz16** [comment]
@jewelljones Good summaries. One thing to add might be a sentence in human capital about how compensating with equity isn't a good way to attract high caliber developers.

**Comment by jewelljones** [comment]
@jsha2007 made an edit based on your comment - thanks.

**Comment by jsha2007** [comment]
looks great! :+1:

**Comment by jewelljones** [comment]
@rmotz16 made edit based on your comment - thanks

**Comment by jewelljones** [comment]
@ck7286 Can you comment here as well?

**Comment by ck7286** [comment]
I agree with the above comments. Great work! :+1:

**Pull request merged**
