### PR TITLE
Create incorporating-the-user.md

### PR DESCRIPTION
**Pull request by rmotz16**
@seankeresey @ck7286 @jewelljones @jsha2007 
What do you think? More emphasis on other phases of incorporating the user? (Like hypothesis testing)

### CODE REVIEW

**Comment by jewelljones** [comment]
@rmotz16 I liked that you incorporated the talk into your notes.  At the very end, you mentioned it makes the team better.  Can you elaborate how so?

**Comment by seankeresey** [comment]
@rmotz16 i like the last sentiment about the the important of the relationship among the entire development team. I think your example adds value, but agree with @jewelljones on integrating more details with respect to making the team better.

**Comment by jsha2007** [comment]
@rmotz16 looks good! but maybe try formatting lines 12-15 so that there is a line break after each statement

**Comment by jewelljones** [comment]
@rmotz16 - Since it's better to merge after the edits are made if needed, I'll merge after getting an okay from you.

**Comment by rmotz16** [comment]
Thanks, I'll wait for @ck7286 to comment, then I'll make the changes above and let you know.

**Comment by ck7286** [comment]
@rmotz16 I like it! Especially the point about customers included. :+1:

**Comment by rmotz16** [comment]
Great - thanks all. I will make the adjustments mentioned and then @mention @jewelljones for an additional sign off.

**Comment by rmotz16** [comment]
@jewelljones and @jsha2007 Good now? Ready to ship?

**Comment by jsha2007** [comment]
looks great now, ready to ship :+1:

**Comment by jewelljones** [comment]
great :+1:

**Pull request merged**
