### PR TITLE
Create Incremental Software Development.md

### PR DESCRIPTION
**Pull request by seankeresey**
Reverts jewelljones/lessons-learned#2

### CODE REVIEW

**Comment by seankeresey** [comment]
@jsha2007 @ck7286 @rmotz16 @jewelljones tell me what you think!

**Comment by rmotz16** [comment]
I like this. I agree - iteration is usually the best way to develop a web-based product or app. Maybe you can mention the idea of a minimum viable product; in case you're working with impatient clients or clients who "just can't see it."

**Comment by jewelljones** [comment]
@seankeresey - Looks ready to ship.  I liked the point of communicating "broad intent".

**Comment by jewelljones** [comment]
@seankeresey - I see two okays here.  I'll merge the request for your page.

**Pull request merged**
