### PR TITLE
Hiring a good developer

### PR DESCRIPTION
**Pull request by jewelljones**
Adding a page to our reposistory

### CODE REVIEW

**Comment by jewelljones** [comment]
@ck7286 @seankeresey @jsha2007 @rmotz16 I figured it out and pulled it back to us (to Jakob's point).  Comment away.

**Comment by seankeresey** [comment]
@ck7286 check spelling and grammar in first sentence.

**Comment by rmotz16** [comment]
@ck7286 I think you nailed it... Succinct and fairly comprehensive, even for a short list. Well done. :+1: from me.

**Comment by seankeresey** [comment]
other than that cheryl is crushing it - dont you think so @jsha2007

**Comment by jsha2007** [comment]
@ck7286 nice use of markdown-styling and summing up what we discussed in class!
@seankeresey i completely agree!!
:+1:

**Comment by ck7286** [comment]
Loving the quick response, team!
@seankeresey @jewelljones I see 2 thumbs up signs... I need more! :8ball:

**Comment by jewelljones** [comment]
@ck7286 I can appreciate that it's to the point.  Maybe add a link for the book: http://www.amazon.com/The-Pragmatic-Programmer-Journeyman-Master/dp/020161622X

**Comment by ck7286** [comment]
@jewelljones great idea! Link added.

**Comment by jewelljones** [comment]
@ck7286 Perfect - I'll merge it to the master.

**Pull request merged**
