### PR TITLE
Create SiteVsApp.md

### PR DESCRIPTION
**Pull request by jsha2007**
@jewelljones @ck7286 @seankeresey @rmotz16 

Any suggestions what I should change?
also, do any of you know why my links don't show up as they are supposed to?

### CODE REVIEW

**Comment by rmotz16** [comment]
@jsha2007 I'm glad you mentioned the "mobile first" approach. I also remember talking about the difficulty with updating apps - mainly, you need users to download the update, whereas, with a website, you can make a change without involving users. Perhaps mention that? (Also, try your links without the line break?)

**Comment by jsha2007** [comment]
@rmotz16 thanks, done!

**Comment by jewelljones** [comment]
@jsha2007 - Where did you get the point about websites taking about 6 weeks and the apps, 2-4 months?  I think it depends on the complexity of them.  For the links, try the following website: http://www.w3schools.com/html/html_links.asp
Me writing the code for you here changes it to the html, so you wouldn't be able to see it ;)

**Comment by jsha2007** [comment]
@jewelljones yes it depends on the complexity, but a good rule of thumb is about 6 weeks for an app (not a website, this should be done faster); I believe I heard in class that with projects of a longer time horizon than 4 months, there usually is a MVP that could be developed first

**Comment by seankeresey** [comment]
@jsha2007 nice use of the link in the last paragraph. It seems like your ready to ship.

**Comment by jewelljones** [comment]
adding my :+1:

**Comment by ck7286** [comment]
Same here... Definitely did not realize all the extra work/costs involved in building an app, until we discussed it in class.

:+1:

**Comment by jewelljones** [comment]
@jsha2007 - Merging this into the master.

**Pull request merged**
