### PR TITLE
Revert "Create Incremental Software Development.md""

### PR DESCRIPTION
**Pull request by jewelljones**
Reverts jewelljones/lessons-learned#6 - adding back as branch for Cheryl to comment

### CODE REVIEW

**Comment by jsha2007** [comment]
@seankeresey maybe add a link that fits better to the topic (since the Biznez logo doesn't really make sense anymore)

**Comment by seankeresey** [comment]
@jsha2007 constructive comment. However, i disagree and would like to move forward with my original artwork.

**Comment by jsha2007** [comment]
:+1:

**Comment by jewelljones** [comment]
:+1:

**Comment by ck7286** [comment]
Looks great Sean :+1:

**Comment by ck7286** [comment]
@jsha2007 agree with your lessons learned. Also, @jewelljones great handling of Github!

**Comment by ck7286** [comment]
@jewelljones nice picture. I agree with @rmotz16 comments above. Hope these tips help you with your future app development! :+1:

**Comment by jewelljones** [comment]
@ck7286 - I think the last comment was meant for another branch, right?

**Comment by jewelljones** [comment]
@rmotz16 - Can you make a comment here as well just to be safe.  Your other one is probably in one of the older patches.

**Comment by rmotz16** [comment]
@seankeresey I believe my comment disappeared into one of the earlier versions - I thought this was great. It's important to have an iterative process. I did think that maybe a mention of building an MVP for antsy clients might round out the topic.

**Comment by jewelljones** [comment]
@seankeresey Do you want to make any changes based on Rachel's comment?

**Comment by seankeresey** [comment]
I did in an earlier version an now I cant edit it. I am fine with it.

**Comment by jewelljones** [comment]
@seankeresey - Got it. Merging now.

**Pull request merged**
